spring:
  datasource:
    url: jdbc:h2:mem:marsroverdb
    username: sss
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

# custom props
mars.cache.dir:       '/tmp/'
mars.photo.seedFile:  '/dates.txt'
nasa.client.apikey:     'DEMO_KEY'
nasa.client.dateFormat: "YYYY-MM-dd"
